# Generated by Django 4.0.4 on 2022-04-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='new_file',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
