# Generated by Django 3.2.6 on 2022-04-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaverse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='body',
        ),
        migrations.AddField(
            model_name='content',
            name='new_file',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
