# Generated by Django 3.2.6 on 2022-04-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaverse', '0002_auto_20220430_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='new_file',
            field=models.FileField(upload_to='media/', verbose_name=''),
        ),
    ]
