# Generated by Django 3.2.6 on 2022-04-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaverse', '0003_alter_content_new_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='new_file',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name=''),
        ),
    ]
