# Generated by Django 3.2.6 on 2022-04-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metaverse', '0004_alter_content_new_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='new_file',
            new_name='file',
        ),
    ]
