# Generated by Django 3.2.6 on 2022-05-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metaverse', '0006_alter_content_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='title',
        ),
    ]
